server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

  cache:
    type: simple

logging:
  level:
    root: info
    org.example: debug