spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

logging:
  level:
    root: warn
    org.example: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
